apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kayaklaunch
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kayaklaunch
        env: test
    spec:
      containers:
      - name: kayaklaunch
        image: kayaklaunch:v1.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kayaklaunch
  labels:
    app: kayaklaunch
    env: test
spec:
  ports:
  - port: 80
  selector:
    app: kayaklaunch
    env: test
  type: LoadBalancer